export default function DesktopRecorderPage() {
  return <section className="grid">
    <div className="hero"><span className="pill">Desktop Recorder MVP</span><h1>VideoBlitzer Recorder</h1><p className="muted">Record matches on your desktop, save WebM locally, upload directly to VideoBlitzer, and queue backend MP4 conversion.</p><div className="tabs"><a className="button" href="/upload">Upload Existing Video</a><a className="button secondary" href="/manual">Read Manual</a></div></div>
    <div className="grid grid-3">
      <div className="card"><h3>Status</h3><p>Desktop Recorder MVP is implemented in the monorepo at <code>apps/desktop-recorder</code>.</p></div>
      <div className="card"><h3>Downloads</h3><p className="muted">Desktop builds will appear here after packaging.</p><p>Package targets: <code>VideoBlitzer-Recorder-mac.dmg</code> and <code>VideoBlitzer-Recorder-win.exe</code>.</p></div>
      <div className="card"><h3>Formats</h3><p>Raw capture: WebM.</p><p>Production export: MP4 through backend FFmpeg conversion.</p></div>
    </div>
    <div className="card"><h3>How it works</h3><p>Select a screen or window, record, save the WebM locally, paste a temporary Supabase access token for private beta testing, then upload through signed URLs generated by the API. R2 credentials stay server-side.</p></div>
  </section>;
}
